#!/usr/bin/env bash
# Install nginx on my server and customize the starting page
# And configure it so that /redirect_me is redirecting to another page (301).

sudo apt-get update
sudo apt-get install nginx -y

sudo mkdir -p /etc/nginx/html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html >/dev/null
printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" | sudo tee /etc/nginx/sites-available/default >/dev/null

sudo service nginx restart
