#!/usr/bin/env bash
# Managing manage_my_process

if [ "$#" -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case $1 in
	"start")
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo manage_my_process started
		;;
	"stop")
		kill "$(cat /var/run/my_process.pid)"
		rm -f /var/run/my_process.pid
		echo manage_my_process stopped
		;;
	"restart")
		kill "$(cat /var/run/my_process.pid)"
		rm -f /var/run/my_process.pid
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo manage_my_process restarted
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
