#!/usr/bin/env bash
# A Bash script that displays `To infinity and beyond` indefinitely and handles SIGTERM

trap 'echo I am invincible!!!' TERM

while true; do
	echo To infinity and beyond
	sleep 2
done

