#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd

pswd="/etc/passwd"

if [ -e "$pswd" ]; then

	exec 3<"$pswd"

	while IFS= read -r line <&3; do
		echo "$line" | cut -d':' -f 1,3,6
	done

	exec 3<&-
fi
