#!/usr/bin/env bash
# This scrpt displays `Best School` 10 times using while loop
# Say also Hi on the 9th line

i=1
while [ $i -le 10 ]; do
	echo "Best School"
	if [ $i == 9 ]; then
		echo Hi
	fi
	((i++))
done
