#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements :
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp -f /etc/hosts ~/hosts.new
sed -i '/localhost/d' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
echo "127.0.0.2	localhost" >> ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
