#!/usr/bin/env bash
# Debug an Apache web server

# Set the ServerName directive globally
echo "ServerName 0.0.0.0:8080" | sudo tee -a /etc/apache2/apache2.conf >/dev/null

# Restart Apache service
sudo service apache2 restart
