#!/usr/bin/env bash
# Run Nginx as the nginx user
sudo service nginx stop
sudo sed -i 's/user.*;/user nginx;/' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx start
