#!/usr/bin/env bash
# Run Nginx as the nginx user in 7 lines or less
sudo sed -i 's/#user.*;/user nginx;/' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/\b80\b/8080/g' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx start
